name: Branch Lint Name CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 18
          - 20
          - 22
        architecture:
          - x64
    name: Branch Lint Name ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
      - run: npm install
      - name: Extract branch name
        shell: bash
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            # For pull requests, use the head branch name
            echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
          else
            # For pushes, extract from GITHUB_REF
            echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          fi
      - name: Check branch name
        run: node ./bin/branch-name-lint .github/branch-name-lint.json
        env:
          GITHUB_BRANCH_NAME: ${{ env.BRANCH_NAME }}
      - run: npm test
